name: FreeRegions
version: '${project.version}'
main: ru.siaw.free.regions.regions.Main
authors: [ tom8hawk ]
website: siaw.ru

commands:
  rg:
    desription: Commands of the plugin itself/business trips
permissions:
  freerg.*:
    default: op
  freerg.reload:
    default: op
  freerg.wand:
    default: op
  freerg.create:
    default: op
  freerg.remove:
    default: op
  freerg.removeAny:
    default: op
  freerg.bypass:
    default: op